services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dumbypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:

